--
-- eAthena Database Converter ( InnoDB -> MyISAM )
--

ALTER TABLE `cart_inventory` ENGINE = MYISAM;
ALTER TABLE `char` ENGINE = MYISAM;
ALTER TABLE `charlog` ENGINE = MYISAM;
ALTER TABLE `friends` ENGINE = MYISAM;
ALTER TABLE `global_reg_value` ENGINE = MYISAM;
ALTER TABLE `guild` ENGINE = MYISAM;
ALTER TABLE `guild_alliance` ENGINE = MYISAM;
ALTER TABLE `guild_castle` ENGINE = MYISAM;
ALTER TABLE `guild_expulsion` ENGINE = MYISAM;
ALTER TABLE `guild_member` ENGINE = MYISAM;
ALTER TABLE `guild_position` ENGINE = MYISAM;
ALTER TABLE `guild_skill` ENGINE = MYISAM;
ALTER TABLE `guild_storage` ENGINE = MYISAM;
ALTER TABLE `homunculus` ENGINE = MYISAM;
ALTER TABLE `interlog` ENGINE = MYISAM;
ALTER TABLE `inventory` ENGINE = MYISAM;
ALTER TABLE `ipbanlist` ENGINE = MYISAM;
ALTER TABLE `item_db` ENGINE = MYISAM;
ALTER TABLE `item_db2` ENGINE = MYISAM;
ALTER TABLE `login` ENGINE = MYISAM;
#ALTER TABLE `loginlog` ENGINE = MYISAM;
#ALTER TABLE `mail` ENGINE = MYISAM;
ALTER TABLE `mapreg` ENGINE = MYISAM;
ALTER TABLE `memo` ENGINE = MYISAM;
ALTER TABLE `mob_db` ENGINE = MYISAM;
ALTER TABLE `mob_db2` ENGINE = MYISAM;
ALTER TABLE `party` ENGINE = MYISAM;
ALTER TABLE `pet` ENGINE = MYISAM;
ALTER TABLE `ragsrvinfo` ENGINE = MYISAM;
ALTER TABLE `sc_data` ENGINE = MYISAM;
ALTER TABLE `skill` ENGINE = MYISAM;
ALTER TABLE `skill_homunculus` ENGINE = MYISAM;
ALTER TABLE `sstatus` ENGINE = MYISAM;
ALTER TABLE `storage` ENGINE = MYISAM;
