ALTER TABLE `mob_db2`
 CHANGE COLUMN `Name` `Sprite` TEXT NOT NULL DEFAULT '',
 CHANGE COLUMN `Name2` `kName` TEXT NOT NULL DEFAULT '',
 ADD COLUMN `iName` TEXT NOT NULL DEFAULT '' AFTER `kName`,
 CHANGE COLUMN `MEXP` `MEXP` MEDIUMINT(9) NOT NULL AFTER `dMotion`,
 CHANGE COLUMN `ExpPer` `ExpPer` SMALLINT(9) NOT NULL AFTER `MEXP`,
 CHANGE COLUMN `MVP1id` `MVP1id` SMALLINT(9) NOT NULL AFTER `ExpPer`,
 CHANGE COLUMN `MVP1per` `MVP1per` SMALLINT(9) NOT NULL AFTER `MVP1id`,
 CHANGE COLUMN `MVP2id` `MVP2id` SMALLINT(9) NOT NULL AFTER `MVP1per`,
 CHANGE COLUMN `MVP2per` `MVP2per` SMALLINT(9) NOT NULL AFTER `MVP2id`,
 CHANGE COLUMN `MVP3id` `MVP3id` SMALLINT(9) NOT NULL AFTER `MVP2per`,
 CHANGE COLUMN `MVP3per` `MVP3per` SMALLINT(9) NOT NULL AFTER `MVP3id`;

UPDATE `mob_db2` SET `iName` = `kName`;
