##########################################################
BASE_OBJ = $(BP)/basealgo.o $(BP)/basearray.o $(BP)/basebuffer.o $(BP)/basecharset.o $(BP)/basefile.o $(BP)/baseheaps.o $(BP)/baseinet.o $(BP)/baselists.o $(BP)/basememory.o $(BP)/baseobjects.o $(BP)/baseparam.o $(BP)/baseparser.o $(BP)/basereentrant.o $(BP)/baseregex.o $(BP)/basesocket.o $(BP)/basesort.o $(BP)/basestrformat.o $(BP)/basestring.o $(BP)/basestrsearch.o $(BP)/basesync.o $(BP)/basethreadpool.o $(BP)/basethreads.o $(BP)/basetime.o $(BP)/basetree.o $(BP)/basetxtdb.o $(BP)/basetypes.o $(BP)/basevariant.o $(BP)/basezlib.o

ifeq ($(findstring -DWITH_MYSQL,$(CPPFLAGS)), -DWITH_MYSQL)
BASE_OBJ += $(BP)/basemysql.o
endif
##########################################################

##########################################################
BASE_H = $(BP)/basealgo.h $(BP)/basearray.h $(BP)/basebuffer.h $(BP)/basecharset.h $(BP)/baseexceptions.h $(BP)/basefile.h $(BP)/baseheaps.h $(BP)/baseinet.h $(BP)/baselib.h $(BP)/baselists.h $(BP)/basememory.h $(BP)/baseministring.h $(BP)/baseobjects.h $(BP)/baseparam.h $(BP)/baseparser.h $(BP)/basepool.h $(BP)/basereentrant.h $(BP)/baseregex.h $(BP)/basesafeptr.h $(BP)/basesocket.h $(BP)/basesort.h $(BP)/basestrformat.h $(BP)/basestring.h $(BP)/basestrsearch.h $(BP)/basesync.h $(BP)/basethreadpool.h $(BP)/basethreads.h $(BP)/basetime.h $(BP)/basetree.h $(BP)/basetxtdb.h $(BP)/basetypes.h $(BP)/basevariant.h $(BP)/basezlib.h

ifeq ($(findstring -DWITH_MYSQL,$(CPPFLAGS)), -DWITH_MYSQL)
BASE_H += $(BP)/basemysql.h
endif
##########################################################
